###
GET http://localhost:8080/mentortools/trainingclass/
Accept: application/json

###

POST http://localhost:8080/mentortools/trainingclass
Content-Type: application/json
Accept: application/json

{
  "title": "azénévfolyamom",
  "start_date": "20201101",
  "end_date": "20210501"
}
